`timescale 1ns/1ps

`include "sdram_pkg.vh"

module sdram_fsm(

    //------------------------------------------------------------
    // Clock / Reset
    //------------------------------------------------------------

    input wire clk,
    input wire rst,


    //------------------------------------------------------------
    // Control Inputs
    //------------------------------------------------------------

    input wire start_read,
    input wire start_write,

    input wire refresh_request,

    input wire timer_done,

    //------------------------------------------------------------
    // Saved Operation Type
    //------------------------------------------------------------
    // This is important.
    //
    // start_read/start_write are request pulses.
    // They may be LOW by the time SDRAM reaches ACTIVATE.
    //
    // op_is_read is generated by sdram_controller from the
    // saved request and therefore remains valid throughout
    // the transaction.
    //------------------------------------------------------------

    input wire op_is_read,


    //------------------------------------------------------------
    // State Outputs
    //------------------------------------------------------------

    output reg [3:0] state,
    output reg [3:0] next_state

);


//============================================================
// STATE REGISTER
//============================================================

always @(posedge clk or posedge rst)
begin

    if (rst)

        state <= `SDRAM_RESET;

    else

        state <= next_state;

end


//============================================================
// NEXT STATE LOGIC
//============================================================

always @(*)
begin

    //--------------------------------------------------------
    // Default
    //--------------------------------------------------------

    next_state = state;


    case(state)


        //====================================================
        // RESET
        //====================================================

        `SDRAM_RESET:
        begin

            if(timer_done)

                next_state = `SDRAM_PRECHARGE;

        end


        //====================================================
        // INITIAL PRECHARGE
        //====================================================

        `SDRAM_PRECHARGE:
        begin

            if(timer_done)

                next_state = `SDRAM_REFRESH1;

        end


        //====================================================
        // REFRESH #1
        //====================================================

        `SDRAM_REFRESH1:
        begin

            if(timer_done)

                next_state = `SDRAM_REFRESH2;

        end


        //====================================================
        // REFRESH #2
        //====================================================

        `SDRAM_REFRESH2:
        begin

            if(timer_done)

                next_state = `SDRAM_MODE;

        end


        //====================================================
        // MODE REGISTER
        //====================================================

        `SDRAM_MODE:
        begin

            if(timer_done)

                next_state = `SDRAM_IDLE;

        end


        //====================================================
        // IDLE
        //====================================================

        `SDRAM_IDLE:
        begin

            //------------------------------------------------
            // Refresh has highest priority
            //------------------------------------------------

            if(refresh_request)

                next_state = `SDRAM_REFRESH1;


            //------------------------------------------------
            // New READ transaction
            //------------------------------------------------

            else if(start_read)

                next_state = `SDRAM_ACTIVATE;


            //------------------------------------------------
            // New WRITE transaction
            //------------------------------------------------

            else if(start_write)

                next_state = `SDRAM_ACTIVATE;

        end


        //====================================================
        // ACTIVATE
        //====================================================
        //
        // IMPORTANT FIX:
        //
        // DO NOT use start_read here.
        //
        // start_read is only the original request signal.
        // By the time ACTIVATE completes, start_read can
        // already be LOW.
        //
        // op_is_read comes from the saved transaction in
        // sdram_controller and remains valid.
        //
        //====================================================

        `SDRAM_ACTIVATE:
        begin

            if(timer_done)
            begin

                //------------------------------------------------
                // Saved transaction was READ
                //------------------------------------------------

                if(op_is_read)

                    next_state = `SDRAM_READ;


                //------------------------------------------------
                // Saved transaction was WRITE
                //------------------------------------------------

                else

                    next_state = `SDRAM_WRITE;

            end

        end


        //====================================================
        // READ
        //====================================================

        `SDRAM_READ:
        begin

            if(timer_done)

                next_state = `SDRAM_PRECHARGE_ROW;

        end


        //====================================================
        // WRITE
        //====================================================

        `SDRAM_WRITE:
        begin

            if(timer_done)

                next_state = `SDRAM_PRECHARGE_ROW;

        end


        //====================================================
        // PRECHARGE AFTER READ / WRITE
        //====================================================

        `SDRAM_PRECHARGE_ROW:
        begin

            if(timer_done)

                next_state = `SDRAM_IDLE;

        end


        //====================================================
        // WAIT
        //====================================================

        `SDRAM_WAIT:
        begin

            if(timer_done)

                next_state = `SDRAM_IDLE;

        end


        //====================================================
        // DEFAULT
        //====================================================

        default:
        begin

            next_state = `SDRAM_RESET;

        end


    endcase

end


endmodule

`include "sdram_pkg.vh"

module refresh_controller(

    //------------------------------------------------------------
    // Clock / Reset
    //------------------------------------------------------------

    input wire clk,
    input wire rst,

    //------------------------------------------------------------
    // Refresh Acknowledge
    //------------------------------------------------------------

    input wire refresh_done,

    //------------------------------------------------------------
    // Refresh Request
    //------------------------------------------------------------

    output reg refresh_request

);

    //------------------------------------------------------------
    // Refresh Counter
    //------------------------------------------------------------

    reg [15:0] refresh_counter;

    //------------------------------------------------------------
    // Counter Logic
    //------------------------------------------------------------

    always @(posedge clk or posedge rst)
    begin

        if(rst)
        begin

            refresh_counter <= 16'd0;

            refresh_request <= 1'b0;

        end

        else
        begin

            //----------------------------------------------------
            // Waiting for Refresh Interval
            //----------------------------------------------------

            if(refresh_counter == (`REFRESH_PERIOD-1))
            begin

                refresh_counter <= 16'd0;

                refresh_request <= 1'b1;

            end

            //----------------------------------------------------
            // Counting
            //----------------------------------------------------

            else
            begin

                refresh_counter <= refresh_counter + 16'd1;

            end

            //----------------------------------------------------
            // Refresh Completed
            //----------------------------------------------------

            if(refresh_done)

                refresh_request <= 1'b0;

        end

    end

endmodule

`include "sdram_pkg.vh"
`include "sdram_pkg.vh"

module sdram_controller(

    //------------------------------------------------------------
    // Clock / Reset
    //------------------------------------------------------------

    input wire clk,
    input wire rst,

    //------------------------------------------------------------
    // CPU Interface
    //------------------------------------------------------------

    input wire read_req,
    input wire write_req,

    input wire [31:0] address,
    input wire [31:0] write_data,

    output reg [31:0] read_data,

    output reg ready,

    //------------------------------------------------------------
    // Refresh Controller
    //------------------------------------------------------------

    input wire refresh_request,

    output reg refresh_done,

    //------------------------------------------------------------
    // SDRAM FSM
    //------------------------------------------------------------

    input wire [3:0] state,

    // FIX: needed so the timing-counter reload below can key off the
    // state being ENTERED rather than the state being left -- see the
    // comment at the reload case statement.
    input wire [3:0] next_state,

    // FIX: timer_done is now an OUTPUT of the controller so sdram_top
    // can feed it back into the FSM. Previously this was a purely
    // internal signal and the FSM's timer_done input was left
    // unconnected (floating), which kept the FSM stuck in
    // SDRAM_RESET forever -- the actual cause of the hang.
    output wire timer_done,

    // FIX: tells the FSM whether the in-flight transaction is a read or
    // write. This stays valid for the whole transaction (latched at
    // request time), unlike start_read/start_write which are only a
    // one-cycle pulse and are long gone by the time the FSM needs to
    // decide READ vs WRITE in ACTIVATE.
    output wire op_is_read,

    //------------------------------------------------------------
    // SDRAM Signals
    //------------------------------------------------------------

    output reg cs_n,
    output reg ras_n,
    output reg cas_n,
    output reg we_n,

    output reg [12:0] sdram_addr,

    output reg [1:0] bank_addr,

    output reg [15:0] dq_out,

    input wire [15:0] dq_in,

    output reg dq_oe

);

//------------------------------------------------------------
// Saved CPU Request
//------------------------------------------------------------

reg [31:0] saved_address;
reg [31:0] saved_write_data;
reg saved_read;
reg saved_write;

// FIX: exposed so sdram_fsm can tell READ from WRITE once it actually
// needs to know (partway through ACTIVATE) -- see the note at the
// `op_is_read` port below.
assign op_is_read = saved_read;

//------------------------------------------------------------
// Row / Column Decode
//------------------------------------------------------------

reg [12:0] row_address;
reg [8:0]  column_address;
reg [1:0]  bank;

always @(*) begin

    row_address = saved_address[23:11];

    column_address = {saved_address[10:2], 1'b0};

    bank = saved_address[25:24];

end
  
//------------------------------------------------------------
// Save CPU Request
//------------------------------------------------------------

always @(posedge clk or posedge rst)
begin
    if(rst)
    begin
        saved_address    <= 32'd0;
        saved_write_data <= 32'd0;
        saved_read       <= 1'b0;
        saved_write      <= 1'b0;
    end
    else
    begin
        if(read_req || write_req)
        begin
            saved_address    <= address;
            saved_write_data <= write_data;
            saved_read       <= read_req;
            saved_write      <= write_req;
        end
    end
end

//------------------------------------------------------------
// Timing Counter (single driver)
//------------------------------------------------------------

reg [3:0] timing_counter;

assign timer_done = (timing_counter == 4'd0);

always @(posedge clk or posedge rst)
begin
    if(rst)
        timing_counter <= 4'd0;
    else
    begin
        if(timing_counter != 4'd0)
            timing_counter <= timing_counter - 4'd1;
        else
        begin
            // FIX: this reload used to key off `state`. Since both this
            // register and the FSM's `state` register update on the same
            // clock edge, using `state` here reads its PRE-edge (old)
            // value -- so the delay loaded always corresponded to the
            // state being LEFT, not the one being entered. That gave every
            // state exactly one "free" cycle where timer_done was already
            // true (timing_counter left over at 0), so WRITE and READ each
            // exited after a single cycle no matter what delay was
            // configured -- never enough time to shift both 16-bit halves.
            // Keying off `next_state` (computed combinationally this same
            // cycle) loads the correct delay starting on cycle 1 of the
            // new state.
            case(next_state)
                `SDRAM_ACTIVATE:
                    timing_counter <= `tRCD;

                `SDRAM_READ:
                    timing_counter <= `CAS_LATENCY + 2;

                // FIX: WRITE previously had no entry here, so
                // timing_counter reloaded to 0 and timer_done was
                // already true the instant WRITE was entered -- the
                // FSM left WRITE after a single cycle, before both
                // halves of the 32-bit word could be shifted out.
                `SDRAM_WRITE:
                    timing_counter <= `tWR;

                `SDRAM_PRECHARGE,
                `SDRAM_PRECHARGE_ROW:
                    timing_counter <= `tRP;

                `SDRAM_REFRESH1,
                `SDRAM_REFRESH2:
                    timing_counter <= `tRFC;

                `SDRAM_MODE:
                    timing_counter <= `tMRD;

                default:
                    timing_counter <= 4'd0;
     
              
            endcase
        end
    end
end

//------------------------------------------------------------
// Read Data Capture
//------------------------------------------------------------

reg [31:0] read_buffer;
reg        read_valid;

always @(posedge clk or posedge rst)
begin

    if(rst)
    begin

        read_buffer <= 32'd0;
        read_data   <= 32'd0;
        read_valid  <= 1'b0;

    end

    else
    begin

        read_valid <= 1'b0;

        if(state == `SDRAM_READ)
        begin

            //------------------------------------------------
            // Capture LOW 16-bit half
            //------------------------------------------------

            if(timing_counter == (`CAS_LATENCY - 1))
            begin

                read_buffer[15:0] <= dq_in;

            end

            //------------------------------------------------
            // Capture HIGH 16-bit half
            //------------------------------------------------

            if(timing_counter == 4'd0)
            begin

                read_data <= {
                    dq_in,
                    read_buffer[15:0]
                };

                read_valid <= 1'b1;

            end

        end

    end

end

//------------------------------------------------------------
// Write Half Select (single driver, sequential only -- no longer
// also assigned combinationally elsewhere)
//------------------------------------------------------------

reg write_half;

always @(posedge clk or posedge rst)
begin
    if(rst)
        write_half <= 1'b0;
    else if(state == `SDRAM_WRITE)
        write_half <= ~write_half;
    else
        write_half <= 1'b0;
end

//------------------------------------------------------------
// SDRAM Command / Output Generator
// (single combinational block: drives cs_n/ras_n/cas_n/we_n,
//  sdram_addr, bank_addr, dq_out, dq_oe, ready, refresh_done)
//------------------------------------------------------------

always @(*) begin

    // Defaults
    cs_n       = 1'b1;
    ras_n      = 1'b1;
    cas_n      = 1'b1;
    we_n       = 1'b1;

    sdram_addr = 13'd0;
    bank_addr  = 2'd0;

    dq_out     = 16'd0;
    dq_oe      = 1'b0;

    refresh_done = 1'b0;

    case(state)

        `SDRAM_RESET:
        begin
            cs_n  = 1'b0;
            ras_n = 1'b1;
            cas_n = 1'b1;
            we_n  = 1'b1;
        end

        `SDRAM_PRECHARGE:
        begin
            cs_n  = 1'b0;
            ras_n = 1'b0;
            cas_n = 1'b1;
            we_n  = 1'b0;
            sdram_addr[10] = 1'b1;
        end

        `SDRAM_REFRESH1,
        `SDRAM_REFRESH2:
        begin
            cs_n  = 1'b0;
            ras_n = 1'b0;
            cas_n = 1'b0;
            we_n  = 1'b1;

            if(state == `SDRAM_REFRESH2 && timer_done)
                refresh_done = 1'b1;
        end

        `SDRAM_MODE:
        begin
            cs_n  = 1'b0;
            ras_n = 1'b0;
            cas_n = 1'b0;
            we_n  = 1'b0;

            sdram_addr =
            {
                3'b000,
                3'd3,
                1'b0,
                3'b010
            };
        end

        `SDRAM_IDLE:
        begin
            // No transaction in flight here; `ready` (a genuine
            // one-shot completion pulse) is now generated in a
            // separate sequential block below, tied to actually
            // leaving SDRAM_PRECHARGE_ROW -- not to merely sitting
            // idle. See that block for the rationale.
        end

        `SDRAM_ACTIVATE:
        begin
            cs_n  = 1'b0;
            ras_n = 1'b0;
            cas_n = 1'b1;
            we_n  = 1'b1;

            sdram_addr = row_address;
            bank_addr  = bank;
        end

        `SDRAM_READ:
        begin
            cs_n  = 1'b0;
            ras_n = 1'b1;
            cas_n = 1'b0;
            we_n  = 1'b1;

            // FIX: hold column_address for the low half, then step to
            // column_address+1 for the high half, so the model (which
            // stores one 16-bit word per address) returns two different
            // words instead of the same one twice. The switch happens
            // once the low half's address has had a full cycle to reach
            // the model (see the capture block above for exact timing).
            if(timing_counter >= (`CAS_LATENCY - 1))
                sdram_addr[8:0] = column_address;
            else
                sdram_addr[8:0] = column_address + 9'd1;

            bank_addr = bank;
        end

        `SDRAM_WRITE:
        begin
            cs_n  = 1'b0;
            ras_n = 1'b1;
            cas_n = 1'b0;
            we_n  = 1'b0;

            // FIX: writes take effect the same cycle the model sees them
            // (no registered latency like reads), so as soon as
            // write_half flips, both address and data flip together --
            // low half goes to column_address, high half to
            // column_address+1.
            if(!write_half)
                sdram_addr[8:0] = column_address;
            else
                sdram_addr[8:0] = column_address + 9'd1;

            bank_addr = bank;

            dq_oe = 1'b1;
            if(!write_half)
                dq_out = saved_write_data[15:0];
            else
                dq_out = saved_write_data[31:16];

           
        end

        `SDRAM_PRECHARGE_ROW:
        begin
            cs_n  = 1'b0;
            ras_n = 1'b0;
            cas_n = 1'b1;
            we_n  = 1'b0;
        end

        default:
        begin
            // NOP
        end

    endcase



end

//------------------------------------------------------------
// `ready` -- genuine one-shot completion pulse
//------------------------------------------------------------
// BUG FIX: `ready` used to be combinational and simply equal to
// (state == SDRAM_IDLE). That is true any time the controller
// happens to be sitting idle, not specifically when the request
// the cache/DMA just issued has actually finished. Two related
// failures came from this:
//
//   1. A write/read could be declared "done" the very same cycle
//      it was first requested (if SDRAM already happened to be
//      idle), long before SDRAM had actually driven any data to
//      or from the array -- letting the cache move on to issue a
//      *new* request while the old one was still mid-flight,
//      corrupting/losing the old one.
//
//   2. A refill read request pulse issued while SDRAM was still
//      busy from a *previous* transaction would be silently
//      dropped (see cache_controller's CACHE_REFILL_REQ/WAIT
//      fix), and the cache would still see a `ready` pulse the
//      moment SDRAM eventually returned to idle for unrelated
//      reasons, latching stale leftover `read_data`.
//
// Every real transaction (read or write) passes through
// SDRAM_PRECHARGE_ROW immediately before returning to
// SDRAM_IDLE. So the correct, unambiguous "this specific
// transaction just completed" signal is a one-cycle pulse fired
// exactly when we leave SDRAM_PRECHARGE_ROW.
//------------------------------------------------------------

always @(posedge clk or posedge rst)
begin

    if(rst)

        ready <= 1'b0;

    else

        ready <= (state == `SDRAM_PRECHARGE_ROW) && timer_done;

end

endmodule

`include "sdram_pkg.vh"

module sdram_top(

    //------------------------------------------------------------
    // Clock / Reset
    //------------------------------------------------------------

    input wire clk,
    input wire rst,

    //------------------------------------------------------------
    // CPU Interface
    //------------------------------------------------------------
    // This is now the ENTIRE external interface of sdram_top. The
    // physical SDRAM pins (cs_n/ras_n/cas_n/we_n/sdram_addr/bank_addr/
    // dq_out/dq_in/dq_oe) used to be ports here too -- which was the
    // actual bug: they were commands going nowhere, because nothing
    // outside sdram_top ever connected them to a memory device.
    // sdram_model is instantiated below instead, so those signals are
    // now purely internal.

    input wire read_req,
    input wire write_req,

    input wire [31:0] address,
    input wire [31:0] write_data,

    output wire [31:0] read_data,

    output wire ready

);

//------------------------------------------------------------
// Internal Signals
//------------------------------------------------------------

wire refresh_request;
wire refresh_done;

wire [3:0] state;
wire [3:0] next_state;

wire timer_done;
wire op_is_read;

//------------------------------------------------------------
// SDRAM Physical Interface (internal only -- no longer external
// ports, since sdram_model is now instantiated right here)
//------------------------------------------------------------

wire cs_n;
wire ras_n;
wire cas_n;
wire we_n;

wire [12:0] sdram_addr;
wire [1:0]  bank_addr;

wire [15:0] dq_out;
wire [15:0] dq_in;

wire dq_oe;

//------------------------------------------------------------
// Refresh Controller
//------------------------------------------------------------

refresh_controller REFRESH(
    .clk(clk),
    .rst(rst),
    .refresh_done(refresh_done),
    .refresh_request(refresh_request)
);

//------------------------------------------------------------
// SDRAM FSM
//------------------------------------------------------------

sdram_fsm FSM(
    .clk(clk),
    .rst(rst),

    .start_read(read_req),
    .start_write(write_req),

    .refresh_request(refresh_request),

    .timer_done(timer_done),
    .op_is_read(op_is_read),

    .state(state),
    .next_state(next_state)
);

//------------------------------------------------------------
// SDRAM Controller
//------------------------------------------------------------

sdram_controller CONTROLLER(
    .clk(clk),
    .rst(rst),

    //--------------------------------------------------------
    // CPU
    //--------------------------------------------------------

    .read_req(read_req),
    .write_req(write_req),

    .address(address),
    .write_data(write_data),

    .read_data(read_data),

    .ready(ready),

    //--------------------------------------------------------
    // Refresh
    //--------------------------------------------------------

    .refresh_request(refresh_request),
    .refresh_done(refresh_done),

    //--------------------------------------------------------
    // FSM
    //--------------------------------------------------------

    .state(state),
    .next_state(next_state),

    .timer_done(timer_done),
    .op_is_read(op_is_read),

    //--------------------------------------------------------
    // SDRAM Pins (now internal wires, connected to sdram_model below
    // instead of dangling as top-level ports)
    //--------------------------------------------------------

    .cs_n(cs_n),
    .ras_n(ras_n),
    .cas_n(cas_n),
    .we_n(we_n),

    .sdram_addr(sdram_addr),
    .bank_addr(bank_addr),

    .dq_out(dq_out),
    .dq_in(dq_in),

    .dq_oe(dq_oe)
);

//------------------------------------------------------------
// SDRAM Memory Device
//------------------------------------------------------------
// FIX: this instantiation is the actual fix for this phase. Without
// it, CONTROLLER's dq_in input floated and every READ returned X --
// the controller was, correctly, generating commands into empty
// space. Note the swap on the data bus: the controller's dq_out
// (what it drives) feeds the model's dq_in (what it samples), and
// vice versa -- same pattern as the original standalone testbench
// that had sdram_top and sdram_model as siblings.

sdram_model MEMORY(
    .clk(clk),

    .cs_n(cs_n),
    .ras_n(ras_n),
    .cas_n(cas_n),
    .we_n(we_n),

    .addr(sdram_addr),
    .bank(bank_addr),

    .dq_in(dq_out),
    .dq_out(dq_in),

    .dq_oe(dq_oe)
);

endmodule

`include "sdram_pkg.vh"

module sdram_model(

    //------------------------------------------------------------
    // Clock
    //------------------------------------------------------------

    input wire clk,

    //------------------------------------------------------------
    // SDRAM Commands
    //------------------------------------------------------------

    input wire cs_n,
    input wire ras_n,
    input wire cas_n,
    input wire we_n,

    //------------------------------------------------------------
    // Address
    //------------------------------------------------------------

    input wire [12:0] addr,

    input wire [1:0] bank,

    //------------------------------------------------------------
    // Data Bus
    //------------------------------------------------------------

    input wire [15:0] dq_in,

    output reg [15:0] dq_out,

    input wire dq_oe

);
  
//------------------------------------------------------------
// SDRAM Memory
//
// 4 Banks × 8192 Rows × 512 Columns
//------------------------------------------------------------

localparam SDRAM_DEPTH =
    `SDRAM_BANKS *
    `SDRAM_ROWS *
    `SDRAM_COLUMNS;

reg [15:0] memory [0:SDRAM_DEPTH-1];

//------------------------------------------------------------
// Physical SDRAM Address
//------------------------------------------------------------

wire [23:0] memory_index;

assign memory_index =
    {
        active_bank,
        active_row,
        addr[8:0]
    };
  
//------------------------------------------------------------
// Active Row
//------------------------------------------------------------

reg [12:0] active_row;
reg [1:0] active_bank;  
reg row_open;
//------------------------------------------------------------
// Initialize
//------------------------------------------------------------

integer i;

initial
begin

    row_open = 1'b0;

    dq_out = 16'd0;

    for(i = 0; i < SDRAM_DEPTH; i = i + 1)

        memory[i]=16'd0;

end
//------------------------------------------------------------
// Command Decode
//------------------------------------------------------------

always @(posedge clk)
begin

    if(!cs_n)
    begin

        //------------------------------------------
        // ACTIVE
        //------------------------------------------

if(!ras_n && cas_n && we_n)
begin

    active_row  <= addr;
    active_bank <= bank;

    row_open <= 1'b1;

end
        //------------------------------------------
        // READ
        //------------------------------------------

        else if(ras_n && !cas_n && we_n)
        begin

            if(row_open)

                dq_out <= memory[memory_index];

        end

        //------------------------------------------
        // WRITE
        //------------------------------------------

        else if(ras_n && !cas_n && !we_n)
        begin

            if(row_open && dq_oe)

                memory[memory_index] <= dq_in;

        end

        //------------------------------------------
        // PRECHARGE
        //------------------------------------------

        else if(!ras_n && cas_n && !we_n)
        begin

            row_open <= 1'b0;

        end

    end

end
endmodule